Update aes_ci.yml to check for tabs and trailing whitespace
### Description
- Assert error in the workflow if there are tabs (instead of spaces) or trailing whitespace

diff --git a/.github/workflows/aes_ci.yml b/.github/workflows/aes_ci.yml
--- a/.github/workflows/aes_ci.yml
+++ b/.github/workflows/aes_ci.yml
@@ -38,6 +38,20 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r pip_requirements.txt
 
+      - name: Check for trailing whitespace and tabs
+        run: |
+          # Check for trailing whitespace
+          if grep -rnI '[[:blank:]]$' --include=\*.{c,cpp,h,py,sh} .; then
+            echo "Error: Trailing whitespace found in the repository!"
+            exit 1
+          fi
+
+          # Check for tab characters instead of spaces
+          if grep -rnI $'\t' --include=\*.{c,cpp,h,py,sh} .; then
+            echo "Error: Tab characters found in the repository! Please use spaces for indentation."
+            exit 1
+          fi
+
       # C/C++ Linter
       - name: C/C++ Linter
         run: |
